### ISSUE TITLE
Cannot find field: location in message cloud.deploymentmanager.autogen.SingleVmDeploymentPackageSpec

### ISSUE THREAD

**Issue by ibrahimkarayel** [GoogleCloudPlatform/deploymentmanager-autogen#75]
Im trying to run 

` --input_type YAML \
  --single_input example-config/solution.yaml \
  --output_type PACKAGE \
  --output solution_folder`

but im getting that error: 

`Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException: Cannot find field: location in message cloud.deploymentmanager.autogen.SingleVmDeploymentPackageSpec
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1500)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1460)
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:2001)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeOneofField(JsonFormat.java:1704)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1663)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1502)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1460)
	at com.google.protobuf.util.JsonFormat$ParserImpl.parseFieldValue(JsonFormat.java:2001)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeField(JsonFormat.java:1665)
	at com.google.protobuf.util.JsonFormat$ParserImpl.mergeMessage(JsonFormat.java:1502)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1460)
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1342)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:477)
	at com.google.cloud.deploymentmanager.autogen.cli.InputReaderFactory$YamlReader.doReadInput(InputReaderFactory.java:97)
	at com.google.cloud.deploymentmanager.autogen.cli.InputReaderFactory$InputReader.readInput(InputReaderFactory.java:57)
	at com.google.cloud.deploymentmanager.autogen.cli.AutogenCli.runAutogen(AutogenCli.java:54)
	at com.google.cloud.deploymentmanager.autogen.cli.AutogenCli.main(AutogenCli.java:76)`

**Comment by ibrahimkarayel** [comment]
it seems some files cached in my local im closing issue
